Regression model

We have build a regression model to predict the most probable prices of the houses in a neighborhood. Based on our observations and analysis to this point, we believe following are the parameters that would be the best choice for evaluating the output. 

Parameters used to train the model

1. Median Income
2. Media TOM
3. Nightlife
4. Education quality
5. 311 data
7. Diversity

We have performed feature scaling on all the parameters to make sure gradient descent converges more quickly- this step includes subtracting mean and then dividing by sdtandard deviation.

In [230]:
import pandas as pd
import numpy as np
import pickle
import scipy.stats as ss
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [328]:
baseline_df = pd.read_csv('../BaltimoreRanking-519/Data/regression_data.csv') #change the path accordingly
baseline_df

,CSA2010,TOM,Crime,Restaurant,Education,Diversity,Price
0,Allendale/Irvington/S. Hilton,43,55.1,9,83.7,24.138062,33250
1,Beechfield/Ten Hills/West Hills,49,46.6,1,87.6,37.403378,130000
2,Belair-Edison,39,56.6,10,79.7,25.807071,41975
3,Brooklyn/Curtis Bay/Hawkins Point,36,54.9,37,74.6,67.740252,40000
4,Canton,30,46.5,90,76.6,29.319447,275000
5,Cedonia/Frankford,45,52.3,16,83.4,38.683630,78575
6,Cherry Hill,38,53.5,4,76.0,12.653485,23500
7,Chinquapin Park/Belvedere,36,47.7,12,80.2,50.699036,120000
8,Claremont/Armistead,57,46.3,2,79.5,67.914420,90000
9,Clifton-Berea,32,55.0,17,62.9,9.107467,20000
10,Cross-Country/Cheswolde,35,14.6,1,85.9,45.488381,165000
11,Dickeyville/Franklintown,126,29.3,1,61.8,24.766417,227550
12,Dorchester/Ashburton,40,56.4,1,84.2,9.750095,86250
13,Downtown/Seton Hill,88,243.3,135,90.3,69.837295,235250
14,Edmondson Village,39,38.9,1,77.3,8.671420,55000
15,Fells Point,33,71.0,105,80.1,56.559462,249000
16,Forest Park/Walbrook,49,50.0,1,81.5,12.003849,65500
17,Glen-Fallstaff,47,51.8,26,82.1,57.698732,87500
18,Greater Charles Village/Barclay,41,68.8,35,80.7,68.722022,189900
19,Greater Govans,44,39.9,2,84.2,19.841083,50600
20,Greater Mondawmin,33,102.9,8,87.3,9.505143,40500
21,Greater Roland Park/Poplar Hill,36,28.2,19,87.9,39.988618,310000
22,Greater Rosemont,54,63.0,23,76.4,8.792759,20000
23,Greenmount East,72,66.5,9,67.8,10.289992,30000
24,Hamilton,45,50.1,7,79.0,56.362675,106000
25,Harbor East/Little Italy,55,159.4,33,64.2,62.857458,298000
26,Harford/Echodale,47,44.2,9,82.3,58.114390,123999
27,Highlandtown,41,88.8,32,70.5,63.841618,265000
28,Howard Park/West Arlington,34,45.3,7,78.5,13.897009,70000
29,Inner Harbor/Federal Hill,28,79.3,179,67.0,37.169210,320000
30,Lauraville,46,38.9,9,85.1,55.731839,132000
31,Loch Raven,34,43.7,3,85.8,25.509003,73100
32,Madison/East End,61,71.8,8,66.5,24.369222,25000
33,Medfield/Hampden/Woodberry/Remington,29,51.5,43,75.9,41.489402,175000
34,Midtown,33,84.2,87,74.7,62.856126,200000
35,Midway/Coldstream,28,69.9,9,82.5,10.763669,17005
36,Morrell Park/Violetville,35,58.8,17,80.6,47.515149,69000
37,Mount Washington/Coldspring,34,30.0,1,88.6,50.435294,287000
38,North Baltimore/Guilford/Homeland,33,29.9,23,71.0,43.495901,325000
39,Northwood,36,41.8,4,83.3,23.717293,90000
40,Oldtown/Middle East,35,82.6,27,76.9,22.005811,149900
41,Orangeville/East Highlandtown,37,81.0,63,78.8,78.724747,90000
42,Patterson Park North & East,28,79.5,7,79.8,77.996021,172000
43,Penn North/Reservoir Hill,36,59.6,8,76.1,20.447967,65000
44,Pimlico/Arlington/Hilltop,48,55.7,18,75.6,13.164896,30000
45,Poppleton/The Terraces/Hollins Market,27,82.0,9,72.8,32.016521,73600
46,Sandtown-Winchester/Harlem Park,39,63.1,6,75.5,8.487372,18000
47,South Baltimore,23,49.8,15,82.9,20.363224,289900
48,Southeastern,65,83.7,11,71.1,74.506326,75000
49,Southern Park Heights,47,51.6,3,78.7,10.500431,19900
50,Southwest Baltimore,54,80.7,36,71.1,44.159298,23250
51,The Waverlies,54,75.2,8,74.3,38.771609,79950
52,Upton/Druid Heights,31,77.9,7,70.8,16.638044,71202
53,Washington Village/Pigtown,36,139.4,3,89.9,62.206198,113000
54,Westport/Mount Winans/Lakeland,30,71.2,6,73.6,63.065274,35500

In [232]:
x_df = baseline_df[['TOM', 'Crime', 'Restaurant', 'Education', 'Diversity']] 
y_dfx_log_df = baseline_df['Price']

In [233]:
x_df.corr()

                 TOM     Crime  Restaurant  Education  Diversity
TOM         1.000000  0.221893   -0.023980  -0.258521   0.043518
Crime       0.221893  1.000000    0.451788  -0.012080   0.313616
Restaurant -0.023980  0.451788    1.000000  -0.128404   0.306724
Education  -0.258521 -0.012080   -0.128404   1.000000   0.096767
Diversity   0.043518  0.313616    0.306724   0.096767   1.000000

We see from the correlation table that features are independent of each other due to low coefficient value except Restaurant and Crime. By doing P test for these two features we see that p value is lw so we can consider both the featues for our model.

In [234]:
restaurant = x_df['Restaurant']
crime = x_df['Crime']
corr, p = ss.pearsonr(restaurant, crime)
print ("R: %s P: %s" %(corr, p))

R: 0.451787704805 P: 0.000535354843477

In [235]:
x_log_df = x_df.copy()
cols = list(x_df.columns)
for col in cols:
    x_log_df[col] = np.log(x_df[col])

y_log_df = np.log(y_df)
x_log_df.head(2)

       TOM     Crime  Restaurant  Education  Diversity
0  3.76120  4.009150    2.197225   4.427239   3.183790
1  3.89182  3.841601    0.000000   4.472781   3.621761

In [306]:
model = LinearRegression(fit_intercept=True, normalize=True, copy_X=True)

In [307]:
X = x_log_df
Y = y_log_df

In [311]:
model = train(model, X, Y)
prediction = test(model, X, Y, True)

Regression coefficients:
 [-0.60500572 -0.20395281  0.09514333  0.51082438  0.83366618]
Bias 9.16
Residual sum of squares: 0.00
Variance score: 0.36

In [312]:
print("Outliers: ")
outliers = [3, 11, 47, 50, 54]
residual[outliers]

Outliers:

3     2.150382
11    1.927199
47    1.616619
50    2.086255
54    1.657367
Name: Price, dtype: float64

In [313]:
X_new = X.drop(outliers)
Y_new = Y.drop(outliers)
X_new.reset_index()
Y_new.reset_index()

X_train = X_new[:40]
X_test = X_new[40:]
Y_train = Y_new[:40]
Y_test = Y_new[40:]

In [314]:
model = train(model, X_new, Y_new)
prediction= test(model, X_test, Y_test, False)

Regression coefficients:
 [-0.60500572 -0.20395281  0.09514333  0.51082438  0.83366618]
Bias 9.16
Residual sum of squares: 0.05
Variance score: 0.78

In [320]:
pickle.dump(model, open('Baltimore_model.sav', 'wb'))

Below code is to train and test the model

In [309]:
def test(model, X_test, Y_test, flag):
    prediction = (model.predict(X_test))
    print("Residual sum of squares: %.2f" % np.mean(prediction - Y_test) ** 2)
    print('Variance score: %.2f' % model.score(X_test, Y_test))
    if flag:
        residual = (prediction - Y_test) ** 2
        #print(residual)
    return prediction
        
def train(model, X_train, Y_train):
        model.fit(X_new, Y_new)
        print('Regression coefficients: \n', model.coef_)
        print('Bias %.2f' % model.intercept_)
        return model